openapi: 3.0.0
info:
    description: This is the swagger OpenAPI file that goes with our sever code
    version: "1.0.0"
    title: Kartavyas Mail Handler

servers:
    - url: /mail
      description: Main production server for exposing API endpoints for mail controllers

paths:
    /handler:
        post:
            operationId: email.controllers.mail_controller.send_mail
            tags:
                - Response
            summary: Add to sender identity and send mail
            description: Recieves form body response and sends mail
            requestBody:
                required: true
                content:
                    application/x-www-form-urlencoded:
                        schema:
                            $ref: '#/components/schemas/FormData'
            responses:
                200:
                    description: Successfully sent mail

components:
    schemas:
        FormData:
            type: object
            properties:
                firstName:
                    type: string
                    description: First name of the sender
                lastName:
                    type: string
                    description: Last name of the sender
                email:
                    type: string
                    description: Email of the sender
                message:
                    type: string
                    description: Message from the sender
