---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: src/content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: 'src/content/:filename:'
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
